#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecka.DENT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ECKADENT")]
	public partial class EckaDentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOPROCESS(OPROCESS instance);
    partial void UpdateOPROCESS(OPROCESS instance);
    partial void DeleteOPROCESS(OPROCESS instance);
    partial void InsertSTOCK(STOCK instance);
    partial void UpdateSTOCK(STOCK instance);
    partial void DeleteSTOCK(STOCK instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public EckaDentDataContext() : 
				base(global::ecka.DENT.Properties.Settings.Default.ECKADENTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EckaDentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EckaDentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EckaDentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EckaDentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OPROCESS> OPROCESSes
		{
			get
			{
				return this.GetTable<OPROCESS>();
			}
		}
		
		public System.Data.Linq.Table<STOCK> STOCKs
		{
			get
			{
				return this.GetTable<STOCK>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<CIKISBILGI> CIKISBILGIs
		{
			get
			{
				return this.GetTable<CIKISBILGI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OPROCESS")]
	public partial class OPROCESS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _processID;
		
		private System.Nullable<int> _stockID;
		
		private System.Nullable<int> _userID;
		
		private System.Nullable<decimal> _Oquantity;
		
		private System.Nullable<System.DateTime> _Odate;
		
		private string _usageArea;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnprocessIDChanging(int value);
    partial void OnprocessIDChanged();
    partial void OnstockIDChanging(System.Nullable<int> value);
    partial void OnstockIDChanged();
    partial void OnuserIDChanging(System.Nullable<int> value);
    partial void OnuserIDChanged();
    partial void OnOquantityChanging(System.Nullable<decimal> value);
    partial void OnOquantityChanged();
    partial void OnOdateChanging(System.Nullable<System.DateTime> value);
    partial void OnOdateChanged();
    partial void OnusageAreaChanging(string value);
    partial void OnusageAreaChanged();
    #endregion
		
		public OPROCESS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int processID
		{
			get
			{
				return this._processID;
			}
			set
			{
				if ((this._processID != value))
				{
					this.OnprocessIDChanging(value);
					this.SendPropertyChanging();
					this._processID = value;
					this.SendPropertyChanged("processID");
					this.OnprocessIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockID", DbType="Int")]
		public System.Nullable<int> stockID
		{
			get
			{
				return this._stockID;
			}
			set
			{
				if ((this._stockID != value))
				{
					this.OnstockIDChanging(value);
					this.SendPropertyChanging();
					this._stockID = value;
					this.SendPropertyChanged("stockID");
					this.OnstockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Int")]
		public System.Nullable<int> userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oquantity", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Oquantity
		{
			get
			{
				return this._Oquantity;
			}
			set
			{
				if ((this._Oquantity != value))
				{
					this.OnOquantityChanging(value);
					this.SendPropertyChanging();
					this._Oquantity = value;
					this.SendPropertyChanged("Oquantity");
					this.OnOquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Odate", DbType="Date")]
		public System.Nullable<System.DateTime> Odate
		{
			get
			{
				return this._Odate;
			}
			set
			{
				if ((this._Odate != value))
				{
					this.OnOdateChanging(value);
					this.SendPropertyChanging();
					this._Odate = value;
					this.SendPropertyChanged("Odate");
					this.OnOdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usageArea", DbType="NVarChar(255)")]
		public string usageArea
		{
			get
			{
				return this._usageArea;
			}
			set
			{
				if ((this._usageArea != value))
				{
					this.OnusageAreaChanging(value);
					this.SendPropertyChanging();
					this._usageArea = value;
					this.SendPropertyChanged("usageArea");
					this.OnusageAreaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STOCK")]
	public partial class STOCK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stockID;
		
		private string _stockGroup;
		
		private string _stockName;
		
		private string _stockCode;
		
		private string _barcode;
		
		private System.Nullable<decimal> _quantity;
		
		private System.Nullable<decimal> _optimumQuantity;
		
		private string _isActive;
		
		private string _warehouse;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstockIDChanging(int value);
    partial void OnstockIDChanged();
    partial void OnstockGroupChanging(string value);
    partial void OnstockGroupChanged();
    partial void OnstockNameChanging(string value);
    partial void OnstockNameChanged();
    partial void OnstockCodeChanging(string value);
    partial void OnstockCodeChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void OnquantityChanging(System.Nullable<decimal> value);
    partial void OnquantityChanged();
    partial void OnoptimumQuantityChanging(System.Nullable<decimal> value);
    partial void OnoptimumQuantityChanged();
    partial void OnisActiveChanging(string value);
    partial void OnisActiveChanged();
    partial void OnwarehouseChanging(string value);
    partial void OnwarehouseChanged();
    #endregion
		
		public STOCK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stockID
		{
			get
			{
				return this._stockID;
			}
			set
			{
				if ((this._stockID != value))
				{
					this.OnstockIDChanging(value);
					this.SendPropertyChanging();
					this._stockID = value;
					this.SendPropertyChanged("stockID");
					this.OnstockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockGroup", DbType="NVarChar(50)")]
		public string stockGroup
		{
			get
			{
				return this._stockGroup;
			}
			set
			{
				if ((this._stockGroup != value))
				{
					this.OnstockGroupChanging(value);
					this.SendPropertyChanging();
					this._stockGroup = value;
					this.SendPropertyChanged("stockGroup");
					this.OnstockGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockName", DbType="NVarChar(50)")]
		public string stockName
		{
			get
			{
				return this._stockName;
			}
			set
			{
				if ((this._stockName != value))
				{
					this.OnstockNameChanging(value);
					this.SendPropertyChanging();
					this._stockName = value;
					this.SendPropertyChanged("stockName");
					this.OnstockNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockCode", DbType="NVarChar(50)")]
		public string stockCode
		{
			get
			{
				return this._stockCode;
			}
			set
			{
				if ((this._stockCode != value))
				{
					this.OnstockCodeChanging(value);
					this.SendPropertyChanging();
					this._stockCode = value;
					this.SendPropertyChanged("stockCode");
					this.OnstockCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(50)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optimumQuantity", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> optimumQuantity
		{
			get
			{
				return this._optimumQuantity;
			}
			set
			{
				if ((this._optimumQuantity != value))
				{
					this.OnoptimumQuantityChanging(value);
					this.SendPropertyChanging();
					this._optimumQuantity = value;
					this.SendPropertyChanged("optimumQuantity");
					this.OnoptimumQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="NVarChar(50)")]
		public string isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warehouse", DbType="NVarChar(50)")]
		public string warehouse
		{
			get
			{
				return this._warehouse;
			}
			set
			{
				if ((this._warehouse != value))
				{
					this.OnwarehouseChanging(value);
					this.SendPropertyChanging();
					this._warehouse = value;
					this.SendPropertyChanged("warehouse");
					this.OnwarehouseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userID;
		
		private string _username;
		
		private string _password;
		
		private string _department;
		
		private string _authority;
		
		private string _isActive;
		
		private string _lastLogin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnauthorityChanging(string value);
    partial void OnauthorityChanged();
    partial void OnisActiveChanging(string value);
    partial void OnisActiveChanged();
    partial void OnlastLoginChanging(string value);
    partial void OnlastLoginChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(50)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authority", DbType="NVarChar(50)")]
		public string authority
		{
			get
			{
				return this._authority;
			}
			set
			{
				if ((this._authority != value))
				{
					this.OnauthorityChanging(value);
					this.SendPropertyChanging();
					this._authority = value;
					this.SendPropertyChanged("authority");
					this.OnauthorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="NVarChar(50)")]
		public string isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLogin", DbType="NVarChar(50)")]
		public string lastLogin
		{
			get
			{
				return this._lastLogin;
			}
			set
			{
				if ((this._lastLogin != value))
				{
					this.OnlastLoginChanging(value);
					this.SendPropertyChanging();
					this._lastLogin = value;
					this.SendPropertyChanged("lastLogin");
					this.OnlastLoginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CIKISBILGI")]
	public partial class CIKISBILGI
	{
		
		private int _ID;
		
		private string _STOKADI;
		
		private System.Nullable<decimal> _CIKISMIKTARI;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _KULLANIMALANI;
		
		private string _KULLANICI;
		
		public CIKISBILGI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this._STOKADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKISMIKTARI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CIKISMIKTARI
		{
			get
			{
				return this._CIKISMIKTARI;
			}
			set
			{
				if ((this._CIKISMIKTARI != value))
				{
					this._CIKISMIKTARI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="Date")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this._TARIH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANIMALANI", DbType="NVarChar(255)")]
		public string KULLANIMALANI
		{
			get
			{
				return this._KULLANIMALANI;
			}
			set
			{
				if ((this._KULLANIMALANI != value))
				{
					this._KULLANIMALANI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICI", DbType="NVarChar(50)")]
		public string KULLANICI
		{
			get
			{
				return this._KULLANICI;
			}
			set
			{
				if ((this._KULLANICI != value))
				{
					this._KULLANICI = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
